/*
 * This file is generated by jOOQ.
 */
package com.uoc.jooq.tables.records


import com.uoc.jooq.tables.Orderitem

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class OrderitemRecord() : UpdatableRecordImpl<OrderitemRecord>(Orderitem.ORDERITEM) {

    open var orderid: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var productid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var quantity: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<String?, String?> = super.key() as Record2<String?, String?>

    /**
     * Create a detached, initialised OrderitemRecord
     */
    constructor(orderid: String? = null, productid: String? = null, quantity: Int? = null): this() {
        this.orderid = orderid
        this.productid = productid
        this.quantity = quantity
        resetChangedOnNotNull()
    }
}
