/*
 * This file is generated by jOOQ.
 */
package com.uoc.jooq.tables.references


import com.uoc.jooq.tables.Address
import com.uoc.jooq.tables.Customer
import com.uoc.jooq.tables.Order
import com.uoc.jooq.tables.Orderitem



/**
 * The table <code>db.Address</code>.
 */
val ADDRESS: Address = Address.ADDRESS

/**
 * The table <code>db.Customer</code>.
 */
val CUSTOMER: Customer = Customer.CUSTOMER

/**
 * The table <code>db.Order</code>.
 */
val ORDER: Order = Order.ORDER

/**
 * The table <code>db.OrderItem</code>.
 */
val ORDERITEM: Orderitem = Orderitem.ORDERITEM
