/*
 * This file is generated by jOOQ.
 */
package com.uoc.jooq.tables


import com.uoc.jooq.Db
import com.uoc.jooq.keys.KEY_ORDERITEM_PRIMARY
import com.uoc.jooq.keys.ORDERITEM_IBFK_1
import com.uoc.jooq.tables.Order.OrderPath
import com.uoc.jooq.tables.records.OrderitemRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Orderitem(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, OrderitemRecord>?,
    parentPath: InverseForeignKey<out Record, OrderitemRecord>?,
    aliased: Table<OrderitemRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<OrderitemRecord>(
    alias,
    Db.DB,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>db.OrderItem</code>
         */
        val ORDERITEM: Orderitem = Orderitem()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<OrderitemRecord> = OrderitemRecord::class.java

    /**
     * The column <code>db.OrderItem.orderId</code>.
     */
    val ORDERID: TableField<OrderitemRecord, String?> = createField(DSL.name("orderId"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>db.OrderItem.productId</code>.
     */
    val PRODUCTID: TableField<OrderitemRecord, String?> = createField(DSL.name("productId"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>db.OrderItem.quantity</code>.
     */
    val QUANTITY: TableField<OrderitemRecord, Int?> = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<OrderitemRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<OrderitemRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<OrderitemRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>db.OrderItem</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>db.OrderItem</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>db.OrderItem</code> table reference
     */
    constructor(): this(DSL.name("OrderItem"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, OrderitemRecord>?, parentPath: InverseForeignKey<out Record, OrderitemRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ORDERITEM, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class OrderitemPath : Orderitem, Path<OrderitemRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, OrderitemRecord>?, parentPath: InverseForeignKey<out Record, OrderitemRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<OrderitemRecord>): super(alias, aliased)
        override fun `as`(alias: String): OrderitemPath = OrderitemPath(DSL.name(alias), this)
        override fun `as`(alias: Name): OrderitemPath = OrderitemPath(alias, this)
        override fun `as`(alias: Table<*>): OrderitemPath = OrderitemPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Db.DB
    override fun getPrimaryKey(): UniqueKey<OrderitemRecord> = KEY_ORDERITEM_PRIMARY
    override fun getReferences(): List<ForeignKey<OrderitemRecord, *>> = listOf(ORDERITEM_IBFK_1)

    private lateinit var _order: OrderPath

    /**
     * Get the implicit join path to the <code>db.Order</code> table.
     */
    fun order(): OrderPath {
        if (!this::_order.isInitialized)
            _order = OrderPath(this, ORDERITEM_IBFK_1, null)

        return _order;
    }

    val order: OrderPath
        get(): OrderPath = order()
    override fun `as`(alias: String): Orderitem = Orderitem(DSL.name(alias), this)
    override fun `as`(alias: Name): Orderitem = Orderitem(alias, this)
    override fun `as`(alias: Table<*>): Orderitem = Orderitem(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Orderitem = Orderitem(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Orderitem = Orderitem(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Orderitem = Orderitem(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Orderitem = Orderitem(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Orderitem = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Orderitem = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Orderitem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Orderitem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Orderitem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Orderitem = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Orderitem = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Orderitem = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Orderitem = where(DSL.notExists(select))
}
